2024-07-06 14:39:46,733 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-07-06 14:39:46,734 - discord.client - INFO - logging in using static token
2024-07-06 14:39:51,373 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:39:51,373 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "1.7681785090254845" seconds.
2024-07-06 14:39:57,229 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:39:57,229 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "3.536357018050969" seconds.
2024-07-06 14:40:04,863 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:40:04,864 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "4.896122588577866" seconds.
2024-07-06 14:40:13,852 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:40:13,852 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "18.67315792142823" seconds.
2024-07-06 14:40:36,628 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:40:36,628 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "30.0" seconds.
2024-07-06 14:41:10,732 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:41:10,732 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "0.4307135912880671" seconds.
2024-07-06 14:41:15,266 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:41:15,266 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "0.8614271825761342" seconds.
2024-07-06 14:41:20,228 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:41:20,228 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "17.76140955210641" seconds.
2024-07-06 14:41:42,100 - wavelink.websocket - WARNING - An unexpected error occurred while connecting Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) to Lavalink: "Cannot connect to host localhost:2333 ssl:default [Il computer remoto ha rifiutato la connessione di rete]"
If this error persists or wavelink is unable to reconnect, please see: https://github.com/PythonistaGuild/Wavelink/issues
2024-07-06 14:41:42,100 - wavelink.websocket - INFO - Node(identifier=f4Dw0Bw5FXEU5OY0, uri=http://localhost:2333, status=NodeStatus.CONNECTING, players=0) retrying websocket connection in "26.767605258579852" seconds.
2024-07-06 14:41:52,623 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000023A64923050>
